### ISSUE TITLE
Release this to Rubygems

### ISSUE THREAD

**Issue by bkerley** [r509/r509-validity-crl#1]
I'm working on https://github.com/bkerley/r509-cert-validator , and it depends on this for testing (running a combination OCSP and CRL endpoint to test against). Is there any plan, schedule, or blockers for releasing this as a gem?

**Comment by reaperhulk** [comment]
No blockers that I'm aware of, so I can certainly release this today if it covers your requirements.

**Comment by reaperhulk** [comment]
Done. [Release post](https://langui.sh/2014/02/11/r509-validity-crl/).

**Comment by bkerley** [comment]
Sweet, thanks!
